// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tiantang_auto_harvest.Models;

#nullable disable

namespace tiantang_auto_harvest.Migrations.PushChannelKeysDb
{
    [DbContext(typeof(PushChannelKeysDbContext))]
    [Migration("20211213061801_AddPushChannelKeys")]
    partial class AddPushChannelKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("tiantang_auto_harvest.Models.PushChannelKeys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerChanSendKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramBotToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerChanSendKey")
                        .IsUnique();

                    b.HasIndex("TelegramBotToken")
                        .IsUnique();

                    b.ToTable("PushChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
