// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tiantang_auto_harvest.Models;

#nullable disable

namespace tiantang_auto_harvest.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20211220033748_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("tiantang_auto_harvest.Models.ProxySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxySettings");
                });

            modelBuilder.Entity("tiantang_auto_harvest.Models.PushChannelKeys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProxyNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerChanSendKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramBotToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerChanSendKey")
                        .IsUnique();

                    b.HasIndex("TelegramBotToken")
                        .IsUnique();

                    b.ToTable("PushChannelKeys");
                });

            modelBuilder.Entity("tiantang_auto_harvest.Models.TiantangLoginInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("TiantangLoginInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
