name: Sync to GitEE

on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:boris1993/tiantang-auto-harvest
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:boris1993/tiantang-auto-harvest
